package com.movieverse.movie.model;

public enum Genre {
    ACTION, ADVENTURE, ANIMATION, BIOGRAPHY, COMEDY, CRIME,
    DOCUMENTARY, DRAMA, FANTASY, HISTORY, HORROR, MUSICAL,
    MYSTERY, ROMANCE, SCI_FI, SPORT, THRILLER, WAR, WESTERN
}
