package com.movieverse.snapshot.model;

public enum SnapshotCategory {
    OPENING_SCENE, CLIMAX, PLOT_TWIST, ACTION_SEQUENCE,
    EMOTIONAL_MOMENT, ICONIC_DIALOGUE, FINAL_SCENE,
    CHARACTER_INTRODUCTION, VISUAL_SPECTACLE, COMIC_RELIEF
}
